src/Entity/Ingestor.php
<?php

namespace App\Entity;

use App\Enum\MessageProtocol;
use App\Enum\SourceType;
use App\Repository\IngestorRepository;
use DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: IngestorRepository::class)]
class Ingestor
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?int $protocol = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $pull_ip = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $pull_port = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $push_port = null;

    #[ORM\Column]
    private ?int $source_type = null;

    #[ORM\Column]
    private ?int $active = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $pending_command = null;

    #[ORM\Column(nullable: true, options: ['default' => 0])]
    private ?int $processed_messages = null;

    #[ORM\Column(nullable: true, options: ['default' => 0])]
    private ?int $total_processed_messages = null;

    #[ORM\Column(nullable: true)]
    private ?DateTimeImmutable $last_message_at = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getProtocol(): ?int
    {
        return $this->protocol;
    }

    public function setProtocol(int $protocol): self
    {
        $this->protocol = $protocol;

        return $this;
    }

    public function getPullIp(): ?string
    {
        return $this->pull_ip;
    }

    public function setPullIp(?string $pull_ip): self
    {
        $this->pull_ip = $pull_ip;

        return $this;
    }

    public function getPullPort(): ?string
    {
        return $this->pull_port;
    }

    public function setPullPort(?string $pull_port): self
    {
        $this->pull_port = $pull_port;

        return $this;
    }

    public function getPushPort(): ?string
    {
        return $this->push_port;
    }

    public function setPushPort(?string $push_port): self
    {
        $this->push_port = $push_port;

        return $this;
    }

    public function getSourceType(): ?int
    {
        return $this->source_type;
    }

    public function setSourceType(int $source_type): self
    {
        $this->source_type = $source_type;

        return $this;
    }

    public function getActive(): ?int
    {
        return $this->active;
    }

    public function setActive(int $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getPendingCommand(): ?string
    {
        return $this->pending_command;
    }

    public function setPendingCommand(?string $pending_command): self
    {
        $this->pending_command = $pending_command;

        return $this;
    }

    public function getProcessedMessages(): ?int
    {
        return $this->processed_messages;
    }

    public function setProcessedMessages(int $processed_messages): self
    {
        $this->processed_messages = $processed_messages;

        return $this;
    }

    public function getTotalProcessedMessages(): ?int
    {
        return $this->total_processed_messages;
    }

    public function setTotalProcessedMessages(int $total_processed_messages): self
    {
        $this->total_processed_messages = $total_processed_messages;

        return $this;
    }

    public function getLastMessageAt(): ?DateTimeImmutable
    {
        return $this->last_message_at;
    }

    public function setLastMessageAt(?DateTimeImmutable $last_message_at): self
    {
        $this->last_message_at = $last_message_at;

        return $this;
    }

    public function getTypeLabel()
    {
        return MessageProtocol::getLabel()[$this->protocol];
    }

    public function getSourceTypeLabel()
    {
        return SourceType::getLabel()[$this->source_type];
    }
}

src/Form/IngestorType.php
<?php

namespace App\Form;

use App\Entity\Ingestor;
use App\Enum\BooleanType;
use App\Enum\MessageProtocol;
use App\Enum\SourceType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class IngestorType extends AbstractType {
	public function buildForm( FormBuilderInterface $builder, array $options ): void {
		$builder
			->add( 'name', null, [
				'label' => false,
				'attr'  => [
					'placeholder' => 'Name',
				],
			] )
			->add( 'protocol', ChoiceType::class, [
				'label'   => false,
				'choices' => MessageProtocol::getChoices(),
			] )
			->add( 'pull_ip' )
			->add( 'pull_port' )
			->add( 'push_port' )
			->add( 'source_type', ChoiceType::class, [
				'label'   => false,
				'choices' => SourceType::getChoices(),
			] )
			->add( 'active', ChoiceType::class, [
				'label'   => false,
				'choices' => BooleanType::getChoicesActiveInactive(),
			] )
			->add( 'pending_command', null, [
				'label'    => false,
				'disabled' => true,
				'attr'     => [
					'readonly' => true,
				],
			] );
	}

	public function configureOptions( OptionsResolver $resolver ): void {
		$resolver->setDefaults( [
			'data_class' => Ingestor::class,
		] );
	}
}

src/Form/Settings/IngestorType.php
<?php

namespace App\Form\Settings;

use App\Entity\Ingestor;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class IngestorType extends AbstractType {
	public function buildForm( FormBuilderInterface $builder, array $options ): void {
		$builder
			->add( 'name' )
			->add( 'type' )
			->add( 'pull_ip' )
			->add( 'pull_port' )
			->add( 'push_port' )
			->add( 'source_type' )
			->add( 'active' )
			->add( 'pending_command' );
	}

	public function configureOptions( OptionsResolver $resolver ): void {
		$resolver->setDefaults( [
			'data_class' => Ingestor::class,
		] );
	}
}

src/Controller/Settings/IngestorController.php
<?php

namespace App\Controller\Settings;

use App\Entity\Ingestor;
use App\Form\IngestorType;
use App\Repository\IngestorRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route( '/settings/ingestor' )]
#[IsGranted( 'ROLE_ADMIN' )]
class IngestorController extends AbstractController {
	#[Route( '/', name: 'app_ingestor_index', methods: [ 'GET' ] )]
	public function index( IngestorRepository $ingestorRepository ): Response {

		$col = [ 'name', 'type', 'source_type', 'active' ];

		return $this->render( 'ingestor/index.html.twig', [
			'ingestors' => $ingestorRepository->findAll(),
			'col'       => $col,
		] );
	}

	#[Route( '/new', name: 'app_ingestor_new', methods: [ 'GET', 'POST' ] )]
	public function new( Request $request, IngestorRepository $ingestorRepository ): Response {
		$ingestor = new Ingestor();
		$form     = $this->createForm( IngestorType::class, $ingestor );
		$form->handleRequest( $request );

		if ( $form->isSubmitted() && $form->isValid() ) {
			$ingestorRepository->save( $ingestor, true );

			return $this->redirectToRoute( 'app_ingestor_index', [], Response::HTTP_SEE_OTHER );
		}

		return $this->renderForm( 'ingestor/new.html.twig', [
			'ingestor' => $ingestor,
			'form'     => $form,
		] );
	}

	#[Route( '/{id}', name: 'app_ingestor_show', methods: [ 'GET' ] )]
	public function show( Ingestor $ingestor ): Response {
		return $this->render( 'ingestor/show.html.twig', [
			'ingestor' => $ingestor,
		] );
	}

	#[Route( '/{id}/edit', name: 'app_ingestor_edit', methods: [ 'GET', 'POST' ] )]
	public function edit( Request $request, Ingestor $ingestor, IngestorRepository $ingestorRepository ): Response {
		$form = $this->createForm( IngestorType::class, $ingestor );
		$form->handleRequest( $request );

		if ( $form->isSubmitted() && $form->isValid() ) {
			$ingestorRepository->save( $ingestor, true );

			return $this->redirectToRoute( 'app_ingestor_index', [], Response::HTTP_SEE_OTHER );
		}

		return $this->renderForm( 'ingestor/edit.html.twig', [
			'ingestor' => $ingestor,
			'form'     => $form,
		] );
	}

	#[Route( '/{id}', name: 'app_ingestor_delete', methods: [ 'POST' ] )]
	public function delete( Request $request, Ingestor $ingestor, IngestorRepository $ingestorRepository ): Response {
		if ( $this->isCsrfTokenValid( 'delete' . $ingestor->getId(), $request->request->get( '_token' ) ) ) {
			$ingestorRepository->remove( $ingestor, true );
		}

		return $this->redirectToRoute( 'app_ingestor_index', [], Response::HTTP_SEE_OTHER );
	}
}

templates/ingestor/_delete_form.html.twig
<form method="post" action="{{ path('app_ingestor_delete', {'id': ingestor.id}) }}"
      onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ingestor.id) }}">
    <button class="btn">Delete</button>
</form>

templates/ingestor/_form.html.twig
<div class="flex h-screen mt-5 justify-center">
    {{ form_start(form,{'attr': {'class': 'w-screen'}}) }}
    {{ form_errors(form) }}

    <div class="grid grid-cols-3 gap-4 mt-4">
        <div class="col-span-2">
            <label for="{{ form.name.vars.id }}" class="text-lg font-bold">{{ form_label(form.name) }}</label>
            {{ form_widget(form.name, {'attr': {'class': 'form-input rounded w-full'}}) }}
        </div>
        <div class="col-span-1">
            <label for="{{ form.active.vars.id }}" class="text-lg font-bold">{{ form_label(form.active) }}</label>
            {{ form_widget(form.active, {'attr': {'class': 'form-input rounded w-full'}}) }}
        </div>
        <div class="col-span-2">
            <label for="{{ form.protocol.vars.id }}" class="text-lg font-bold">{{ form_label(form.protocol) }}</label>
            {{ form_widget(form.protocol, {'attr': {'class': 'form-input rounded w-full'}}) }}
        </div>
        <div class="col-span-1">
            <label for="{{ form.source_type.vars.id }}"
                   class="text-lg font-bold">{{ form_label(form.source_type) }}</label>
            {{ form_widget(form.source_type, {'attr': {'class': 'form-input rounded w-full'}}) }}
        </div>
        <div class="col-span-1">
            <label for="{{ form.pull_ip.vars.id }}" class="text-lg font-bold">{{ form_label(form.pull_ip) }}</label>
            {{ form_widget(form.pull_ip, {'attr': {'class': 'form-input rounded w-full'}}) }}
        </div>
        <div class="col-span-1">
            <label for="{{ form.pull_port.vars.id }}" class="text-lg font-bold">{{ form_label(form.pull_port) }}</label>
            {{ form_widget(form.pull_port, {'attr': {'class': 'form-input rounded w-full'}}) }}
        </div>
        <div class="col-span-1">
            <label for="{{ form.push_port.vars.id }}" class="text-lg font-bold">{{ form_label(form.push_port) }}</label>
            {{ form_widget(form.push_port, {'attr': {'class': 'form-input rounded w-full'}}) }}
        </div>
        <div class="col-span-3">
            <label for="{{ form.pending_command.vars.id }}"
                   class="text-lg font-bold">{{ form_label(form.pending_command) }}</label>
            {{ form_widget(form.pending_command, {'attr': {'class': 'form-input rounded w-full'}}) }}
        </div>
    </div>
    <div class="mt-8">
        <button type="submit"
                class="btn bg-blue-500 text-white rounded-full px-4 py-2">{{ button_label|default('Save') }}</button>
    </div>
    {{ form_end(form) }}
</div>

templates/ingestor/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Ingestor{% endblock %}

{% block body %}
    <div class="p-7 w-screen h-screen">
        <h1 class="font-bold text-2xl">Edit Ingestor</h1>
        {{ include('ingestor/_form.html.twig', {'button_label': 'Update'}) }}


        {{ include('ingestor/_delete_form.html.twig') }}
    </div>

{% endblock %}

templates/ingestor/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ingestor index{% endblock %}

{% block body %}
    <h1 class="font-bold text-2xl">Ingestor Settings</h1>
    <p>Ingestors are the datasources that provide information to IntelHub</p>
    <table class="table-auto w-full">
        <thead>
        <tr class="bg-gray-300">
            <th class="px-4 py-2 w-1/4">Name</th>
            <th class="px-4 py-2 w-1/4">Type</th>
            <th class="px-4 py-2 w-1/4">Source Type</th>
            <th class="px-4 py-2 w-1/4">Status</th>
            <th class="px-4 py-2 w-1/4">Edit</th>
        </tr>
        </thead>
        <tbody>
        {% for ingestor in ingestors %}
            <tr class="bg-gray-100 text-center">
                <td class="border px-4 py-2 w-1/4">{{ ingestor.name }}</td>
                <td class="border px-4 py-2 w-1/4">{{ ingestor.typeLabel }}</td>
                <td class="border px-4 py-2 w-1/4">{{ ingestor.sourceTypeLabel }}</td>
                <td class="border px-4 py-2 w-1/4">
                    {% if ingestor.active == 1 %}
                        <span class="rounded-full p-2 bg-green-500 text-white">Enabled</span>
                    {% else %}
                        <span class="rounded-full p-2 bg-red-500 text-white">Disabled</span>
                    {% endif %}
                </td>
                <td class="border px-4 py-2 w-1/4">
                    <a href="{{ path('app_ingestor_edit', {'id': ingestor.id}) }}"
                       class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                        Edit
                    </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <a href="{{ path('app_ingestor_new') }}" class="text-white p-2 bg-green-500 rounded">Create new</a>

{% endblock %}

templates/ingestor/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Ingestor{% endblock %}

{% block body %}
    <div class="p-7 w-screen h-screen">
        <h1 class="font-bold text-2xl">Create new Ingestor</h1>
        {{ include('ingestor/_form.html.twig') }}

    </div>
{% endblock %}

templates/ingestor/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ingestor{% endblock %}

{% block body %}
    <h1>Ingestor</h1>

    <table class="table">
        <tbody>
        <tr>
            <th>Id</th>
            <td>{{ ingestor.id }}</td>
        </tr>
        <tr>
            <th>Name</th>
            <td>{{ ingestor.name }}</td>
        </tr>
        <tr>
            <th>Type</th>
            <td>{{ ingestor.type }}</td>
        </tr>
        <tr>
            <th>Pull_ip</th>
            <td>{{ ingestor.pullIp }}</td>
        </tr>
        <tr>
            <th>Pull_port</th>
            <td>{{ ingestor.pullPort }}</td>
        </tr>
        <tr>
            <th>Push_port</th>
            <td>{{ ingestor.pushPort }}</td>
        </tr>
        <tr>
            <th>Source_type</th>
            <td>{{ ingestor.sourceType }}</td>
        </tr>
        <tr>
            <th>Active</th>
            <td>{{ ingestor.active }}</td>
        </tr>
        <tr>
            <th>Pending_command</th>
            <td>{{ ingestor.pendingCommand }}</td>
        </tr>
        </tbody>
    </table>

    <a href="{{ path('app_ingestor_index') }}">back to list</a>

    <a href="{{ path('app_ingestor_edit', {'id': ingestor.id}) }}">edit</a>

    {{ include('ingestor/_delete_form.html.twig') }}
{% endblock %}