src/Entity/Airport.php
<?php

namespace App\Entity;

use App\Repository\AirportRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AirportRepository::class)]
class Airport
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $ident = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $type = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $name = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 5)]
    private ?string $latitude = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 5)]
    private ?string $longitude = null;

    #[ORM\Column(nullable: true)]
    private ?int $elevation_ft = null;

    #[ORM\Column]
    private ?bool $scheduled_service = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $icao = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $iata = null;

    #[ORM\Column(nullable: true)]
    private ?int $external_id = null;

    #[ORM\OneToMany(mappedBy: 'airport', targetEntity: AirportFrequency::class, orphanRemoval: true)]
    private Collection $airportFrequencies;

    #[ORM\OneToMany(mappedBy: 'airport', targetEntity: AirportRunway::class)]
    private Collection $airportRunways;

    public function __construct()
    {
        $this->airportFrequencies = new ArrayCollection();
        $this->airportRunways = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdent(): ?string
    {
        return $this->ident;
    }

    public function setIdent(?string $ident): self
    {
        $this->ident = $ident;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLatitude(): ?string
    {
        return $this->latitude;
    }

    public function setLatitude(string $latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude(): ?string
    {
        return $this->longitude;
    }

    public function setLongitude(string $longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }

    public function getElevationFt(): ?int
    {
        return $this->elevation_ft;
    }

    public function setElevationFt(?int $elevation_ft): self
    {
        $this->elevation_ft = $elevation_ft;

        return $this;
    }

    public function isScheduledService(): ?bool
    {
        return $this->scheduled_service;
    }

    public function setScheduledService(bool $scheduled_service): self
    {
        $this->scheduled_service = $scheduled_service;

        return $this;
    }

    public function getIcao(): ?string
    {
        return $this->icao;
    }

    public function setIcao(?string $icao): self
    {
        $this->icao = $icao;

        return $this;
    }

    public function getIata(): ?string
    {
        return $this->iata;
    }

    public function setIata(?string $iata): self
    {
        $this->iata = $iata;

        return $this;
    }

    public function getExternalId(): ?int
    {
        return $this->external_id;
    }

    public function setExternalId(?int $external_id): self
    {
        $this->external_id = $external_id;

        return $this;
    }

    /**
     * @return Collection<int, AirportFrequency>
     */
    public function getAirportFrequencies(): Collection
    {
        return $this->airportFrequencies;
    }

    public function addAirportFrequency(AirportFrequency $airportFrequency): self
    {
        if (!$this->airportFrequencies->contains($airportFrequency)) {
            $this->airportFrequencies->add($airportFrequency);
            $airportFrequency->setAirport($this);
        }

        return $this;
    }

    public function removeAirportFrequency(AirportFrequency $airportFrequency): self
    {
        if ($this->airportFrequencies->removeElement($airportFrequency)) {
            // set the owning side to null (unless already changed)
            if ($airportFrequency->getAirport() === $this) {
                $airportFrequency->setAirport(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, AirportRunway>
     */
    public function getAirportRunways(): Collection
    {
        return $this->airportRunways;
    }

    public function addAirportRunway(AirportRunway $airportRunway): self
    {
        if (!$this->airportRunways->contains($airportRunway)) {
            $this->airportRunways->add($airportRunway);
            $airportRunway->setAirport($this);
        }

        return $this;
    }

    public function removeAirportRunway(AirportRunway $airportRunway): self
    {
        if ($this->airportRunways->removeElement($airportRunway)) {
            // set the owning side to null (unless already changed)
            if ($airportRunway->getAirport() === $this) {
                $airportRunway->setAirport(null);
            }
        }

        return $this;
    }

    public function userFriendlyType(): string
    {
        switch ($this->type) {
            case 'large_airport':
                return 'Large Airport';
            case 'medium_airport':
                return 'Medium Airport';
            case 'small_airport':
                return 'Small Airport';
            case 'closed':
                return 'Closed';
            case 'heliport':
                return 'Heliport';
            case 'balloonport':
                return 'Balloonport';
            case 'seaplane_base':
                return 'Seaplane Base';
            default:
                return 'Unknown';
        }
    }
}

src/Entity/AirportRunway.php
<?php

namespace App\Entity;

use App\Repository\AirportRunwayRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AirportRunwayRepository::class)]
class AirportRunway
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'airportRunways')]
    private ?Airport $airport = null;

    #[ORM\Column(nullable: true)]
    private ?int $lenght_ft = null;

    #[ORM\Column(nullable: true)]
    private ?int $width_ft = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $surface = null;

    #[ORM\Column]
    private ?bool $lighted = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $le_ident = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $he_ident = null;

    #[ORM\Column(nullable: true)]
    private ?int $external_id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAirport(): ?Airport
    {
        return $this->airport;
    }

    public function setAirport(?Airport $airport): self
    {
        $this->airport = $airport;

        return $this;
    }

    public function getLenghtFt(): ?int
    {
        return $this->lenght_ft;
    }

    public function setLenghtFt(?int $lenght_ft): self
    {
        $this->lenght_ft = $lenght_ft;

        return $this;
    }

    public function getWidthFt(): ?int
    {
        return $this->width_ft;
    }

    public function setWidthFt(?int $width_ft): self
    {
        $this->width_ft = $width_ft;

        return $this;
    }

    public function getSurface(): ?string
    {
        return $this->surface;
    }

    public function setSurface(?string $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function isLighted(): ?bool
    {
        return $this->lighted;
    }

    public function setLighted(bool $lighted): self
    {
        $this->lighted = $lighted;

        return $this;
    }

    public function getLeIdent(): ?string
    {
        return $this->le_ident;
    }

    public function setLeIdent(?string $le_ident): self
    {
        $this->le_ident = $le_ident;

        return $this;
    }

    public function getHeIdent(): ?string
    {
        return $this->he_ident;
    }

    public function setHeIdent(?string $he_ident): self
    {
        $this->he_ident = $he_ident;

        return $this;
    }

    public function getExternalId(): ?int
    {
        return $this->external_id;
    }

    public function setExternalId(?int $external_id): self
    {
        $this->external_id = $external_id;

        return $this;
    }
}

src/Form/AirportType.php
<?php

namespace App\Form;

use App\Entity\Airport;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AirportType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('ident')
            ->add('type')
            ->add('name')
            ->add('latitude')
            ->add('longitude')
            ->add('elevation_ft')
            ->add('scheduled_service')
            ->add('icao')
            ->add('iata')
            ->add('external_id');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Airport::class,
        ]);
    }
}

src/Controller/AirportController.php
<?php

namespace App\Controller;

use App\Entity\Airport;
use App\Form\AirportType;
use App\Repository\AirportRepository;
use Pagerfanta\Doctrine\ORM\QueryAdapter;
use Pagerfanta\Pagerfanta;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/airport')]
class AirportController extends AbstractController
{
    #[Route('/', name: 'app_airport_index', methods: ['GET'])]
    public function index(AirportRepository $airportRepository, Request $request): Response
    {
        $queryBuilder = $airportRepository->createQueryBuilder('a');
        $query = $request->get('q');
        if ($query) {
            $queryBuilder
                ->andWhere('a.icao LIKE :query')
                ->orWhere('a.iata LIKE :query')
                ->orWhere('UPPER(a.name) LIKE :query')
                ->setParameter('query', '%' . strtoupper($query) . '%');
        }
        $adapter = new QueryAdapter($queryBuilder);
        $pagerFanta = Pagerfanta::createForCurrentPageWithMaxPerPage($adapter, $request->get('page', 1), 20);

        return $this->render('airport/index.html.twig', [
            'airports' => $pagerFanta,
            'query' => $query,
        ]);
    }

    #[Route('/new', name: 'app_airport_new', methods: ['GET', 'POST'])]
    public function new(Request $request, AirportRepository $airportRepository): Response
    {
        $airport = new Airport();
        $form = $this->createForm(AirportType::class, $airport);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $airportRepository->save($airport, true);

            return $this->redirectToRoute('app_airport_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('airport/new.html.twig', [
            'airport' => $airport,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_airport_show', methods: ['GET'])]
    public function show(Airport $airport): Response
    {
        return $this->render('airport/show.html.twig', [
            'airport' => $airport,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_airport_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Airport $airport, AirportRepository $airportRepository): Response
    {
        $form = $this->createForm(AirportType::class, $airport);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $airportRepository->save($airport, true);

            return $this->redirectToRoute('app_airport_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('airport/edit.html.twig', [
            'airport' => $airport,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_airport_delete', methods: ['POST'])]
    public function delete(Request $request, Airport $airport, AirportRepository $airportRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $airport->getId(), $request->request->get('_token'))) {
            $airportRepository->remove($airport, true);
        }

        return $this->redirectToRoute('app_airport_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/airport/_delete_form.html.twig
<form method="post"
      action="{{ path('app_airport_delete', {'id': airport.id}) }}"
      onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden"
           name="_token"
           value="{{ csrf_token('delete' ~ airport.id) }}">
    <button class="btn">Delete</button>
</form>

templates/airport/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
<button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/airport/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Airport{% endblock %}

{% block body %}
    <h1>Edit Airport</h1>

    {{ include('airport/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_airport_index') }}">back to list</a>

    {{ include('airport/_delete_form.html.twig') }}
{% endblock %}

templates/airport/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Airport index{% endblock %}

{% block body %}
    <h2 class="intro-y text-lg font-medium mt-10">
        Airport </h2>
    <div class="intro-y col-span-12 flex flex-wrap sm:flex-nowrap items-center mt-2">
        <div class="w-full sm:w-auto mt-3 sm:mt-0 sm:ml-auto md:ml-0">
            <div class="w-56 relative text-slate-500">
                <form action="{{ path('app_airport_index') }}"
                      method="get">
                    <input type="text"
                           name="q"
                           class="form-control w-56 box pr-10"
                           placeholder="Search"
                           value="{{ query }}">
                </form>
                <i class="w-4 h-4 absolute my-auto inset-y-0 mr-3 right-0"
                   data-lucide="search"></i>
            </div>
        </div>
    </div>
    <div class="intro-y col-span-12 overflow-auto lg:overflow-visible">
        <table class="table table-report -mt-2">
            <thead>
            <tr>
                <th class="text-center whitespace-nowrap">ICAO</th>
                <th class="text-center whitespace-nowrap">IATA</th>
                <th class="text-center whitespace-nowrap">NAME</th>
                <th class="text-center whitespace-nowrap">TYPE</th>
                <th class="text-center whitespace-nowrap">ACTIONS</th>
            </tr>
            </thead>
            <tbody>
            {% for airport in airports %}
                <tr class="intro-x">
                    <td class="text-center">{{ airport.icao }}</td>
                    <td class="text-center">{{ airport.iata }}</td>
                    <td class="text-center">{{ airport.name }}</td>
                    <td class="text-center">{{ airport.userFriendlyType }}</td>
                    <td class="table-report__action w-56">
                        <div class="flex justify-center items-center">
                            <a class="flex items-center mr-3"
                               href="{{ path('app_airport_show', {'id': airport.id}) }}">
                                <i data-lucide="eye"
                                   class="w-4 h-4 mr-1"></i> View
                            </a>
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    {{ pagerfanta(airports) }}
{% endblock %}

templates/airport/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Airport{% endblock %}

{% block body %}
    <h1>Create new Airport</h1>

    {{ include('airport/_form.html.twig') }}

    <a href="{{ path('app_airport_index') }}">back to list</a>
{% endblock %}

templates/airport/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Airport{% endblock %}


{% block body %}
    <div class="grid grid-cols-12 gap-5 mt-5">
        <!-- BEGIN: Profile Cover -->
        <div class="col-span-12">
            <div class="box intro-y px-3 pt-3 pb-5">
                <div class="image-fit h-80 before:content-[''] before:absolute before:w-full before:h-full before:bg-gradient-to-b from-black/20 to-black before:rounded-md before:z-10 ">
                    {#                    <img alt="" #}
                    {#                         class="rounded-md md:object-[0px_-170px]" #}
                    {#                         src="dist/images/preview-16.jpg"> #}
                </div>
                <div class="flex flex-col 2xl:flex-row items-center justify-center text-center 2xl:text-left">
                    <div class="-mt-20 2xl:-mt-10 2xl:ml-10 z-20">
                        <div class="image-fit w-40 h-40 rounded-full border-4 border-white shadow-md overflow-hidden">
                            <img alt=""
                                 src="https://via.placeholder.com/150">
                        </div>
                    </div>
                    <div class="2xl:ml-5">
                        <h2 class="text-2xl mt-5 font-medium">
                            {{ airport.name }}
                        </h2>
                        <div class="mt-2 text-slate-500 flex items-center justify-center 2xl:justify-start">
                            <i data-lucide="briefcase"
                               class="w-4 h-4 mr-2"></i> {{ airport.userFriendlyType }}
                        </div>
                        <div class="mt-2 text-slate-500 flex items-center justify-center 2xl:justify-start">
                            <i data-lucide="camera"
                               class="w-4 h-4 mr-2"></i>


                        </div>
                    </div>
                    <div class="mx-auto grid grid-cols-3 gap-y-2 md:gap-y-0 gap-x-5 h-20 mt-5 2xl:border-l 2xl:border-r border-dashed border-slate-200 px-10 mb-6 2xl:mb-0">
                        <div class="col-span-2 md:col-span-1 flex items-center justify-center 2xl:justify-start">
                            <i data-lucide="map-pin"
                               class="w-4 h-4 mr-2"></i> {{ airport.latitude }}, {{ airport.longitude }}
                        </div>
                        <div class="col-span-2 md:col-span-1 flex items-center justify-center 2xl:justify-start">
                            <i data-lucide="plane"
                               class="w-4 h-4 mr-2"></i> {{ airport.iata | default('No IATA') }}
                        </div>
                        <div class="col-span-2 md:col-span-1 flex items-center justify-center 2xl:justify-start">
                            <i data-lucide="hash"
                               class="w-4 h-4 mr-2"></i> {{ airport.icao }}
                        </div>
                        <div class="col-span-2 md:col-span-1 flex items-center justify-center 2xl:justify-start">
                            <i data-lucide="briefcase"
                               class="w-4 h-4 mr-2"></i> {{ airport.userFriendlyType }}
                        </div>
                        <div class="col-span-2 md:col-span-1 flex items-center justify-center 2xl:justify-start">
                            <i data-lucide="mountain"
                               class="w-4 h-4 mr-2"></i> {{ airport.elevationFt }}
                        </div>
                        <div class="col-span-2 md:col-span-1 flex items-center justify-center 2xl:justify-start">
                            <i data-lucide="clock"
                               class="w-4 h-4 mr-2"></i> {{ airport.scheduledService == 1 ? 'Scheduled Service' : 'No Scheduled Service' }}
                        </div>
                    </div>
                    <div class="flex 2xl:mr-10 mt-5">
                        {#                        <button class="btn btn-primary mr-2 w-32"> #}
                        {#                            <i class="w-4 h-4 mr-2" #}
                        {#                               data-lucide="user-plus"></i> Follow #}
                        {#                        </button> #}
                        {% if is_granted('ROLE_ADMIN', app.user) %}
                            <a class="btn btn-outline-secondary w-32"
                               href="{{ path('app_airport_edit', {'id': airport.id}) }}">
                                <i class="w-4 h-4 mr-2"
                                   data-lucide="pencil"></i> Edit
                            </a>

                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-span-6 xl:col-span-6">
            <div class="box intro-y p-5">
                <div class="flex items-center border-b border-slate-200/60 dark:border-darkmode-400 pb-5 mb-5">
                    <div class="font-medium truncate text-base">Radio Frequencies</div>
                </div>
                <div>
                    <div class="intro-y col-span-12 overflow-auto lg:overflow-visible">
                        {% if airport.airportFrequencies | length > 0 %}
                            <table class="table table-report -mt-2">
                                <thead>
                                <tr>
                                    <th class="text-center whitespace-nowrap">FREQUENCY</th>
                                    <th class="text-center whitespace-nowrap">TYPE</th>
                                    <th class="text-center whitespace-nowrap">DESCRIPTION</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for frequency in airport.airportFrequencies %}
                                    <tr class="intro-x">
                                        <td class="text-center">{{ frequency.frequency }}</td>
                                        <td class="text-center">{{ frequency.type }}</td>
                                        <td class="text-center">{{ frequency.description }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>

                        {% else %}
                            <div class="text-center h-250">
                                <div class="font-medium text-base">No Frequencies</div>
                                <div class="mt-1 text-slate-500">No frequency information is available for this Airport</div>
                            </div>
                        {% endif %}
                    </div>


                </div>
            </div>
        </div>
        <div class="col-span-6 xl:col-span-6">
            <div class="box intro-y p-5">
                <div class="flex items-center border-b border-slate-200/60 dark:border-darkmode-400 pb-5 mb-5">
                    <div class="font-medium truncate text-base">Runways</div>
                </div>
                <div>
                    <div class="intro-y col-span-12 overflow-auto lg:overflow-visible">
                        {% if airport.airportFrequencies | length > 0 %}
                            <table class="table table-report -mt-2">
                                <thead>
                                <tr>
                                    <th class="text-center whitespace-nowrap">HE #</th>
                                    <th class="text-center whitespace-nowrap">LE #</th>
                                    <th class="text-center whitespace-nowrap">LENGHT (ft)</th>
                                    <th class="text-center whitespace-nowrap">WIDTH (ft)</th>
                                    <th class="text-center whitespace-nowrap">SURFACE</th>
                                    <th class="text-center whitespace-nowrap">LIGHTED</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for runway in airport.airportRunways %}
                                    <tr class="intro-x">
                                        <td class="text-center">{{ runway.heIdent }}</td>
                                        <td class="text-center">{{ runway.leIdent }}</td>
                                        <td class="text-center">{{ runway.lenghtFt }}</td>
                                        <td class="text-center">{{ runway.widthFt }}</td>
                                        <td class="text-center">{{ runway.surface }}</td>
                                        <td class="text-center">{{ runway.isLighted == 1 ? 'Yes' : 'No' }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>

                        {% else %}
                            <div class="text-center h-250">
                                <div class="font-medium text-base">No Runways</div>
                                <div class="mt-1 text-slate-500">No runway information is available for this Airport</div>
                            </div>
                        {% endif %}
                    </div>


                </div>
            </div>
        </div>
    </div>

{% endblock %}