src/Entity/Aircraft.php
<?php

namespace App\Entity;

use App\Repository\AircraftRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AircraftRepository::class)]
class Aircraft
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $icao = null;

    #[ORM\Column]
    private ?bool $is_military = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $registration = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $country = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $manufacturer = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $model = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $model_icao = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $operator = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $operator_icao = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $serial = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $year_build = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $picture_url = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $last_data_update_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $last_picture_update_at = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $photo_author = null;

    #[ORM\Column(length: 1000, nullable: true)]
    private ?string $photo_link = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $created_at = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIcao(): ?string
    {
        return $this->icao;
    }

    public function setIcao(string $icao): self
    {
        $this->icao = $icao;

        return $this;
    }

    public function isIsMilitary(): ?bool
    {
        return $this->is_military;
    }

    public function setIsMilitary(bool $is_military): self
    {
        $this->is_military = $is_military;

        return $this;
    }

    public function getRegistration(): ?string
    {
        return $this->registration;
    }

    public function setRegistration(?string $registration): self
    {
        $this->registration = $registration;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getManufacturer(): ?string
    {
        return $this->manufacturer;
    }

    public function setManufacturer(?string $manufacturer): self
    {
        $this->manufacturer = $manufacturer;

        return $this;
    }

    public function getModel(): ?string
    {
        return $this->model;
    }

    public function setModel(?string $model): self
    {
        $this->model = $model;

        return $this;
    }

    public function getModelIcao(): ?string
    {
        return $this->model_icao;
    }

    public function setModelIcao(?string $model_icao): self
    {
        $this->model_icao = $model_icao;

        return $this;
    }

    public function getOperator(): ?string
    {
        return $this->operator;
    }

    public function setOperator(?string $operator): self
    {
        $this->operator = $operator;

        return $this;
    }

    public function getOperatorIcao(): ?string
    {
        return $this->operator_icao;
    }

    public function setOperatorIcao(?string $operator_icao): self
    {
        $this->operator_icao = $operator_icao;

        return $this;
    }

    public function getSerial(): ?string
    {
        return $this->serial;
    }

    public function setSerial(?string $serial): self
    {
        $this->serial = $serial;

        return $this;
    }

    public function getYearBuild(): ?string
    {
        return $this->year_build;
    }

    public function setYearBuild(?string $year_build): self
    {
        $this->year_build = $year_build;

        return $this;
    }

    public function getPictureUrl(): ?string
    {
        return $this->picture_url;
    }

    public function setPictureUrl(?string $picture_url): self
    {
        $this->picture_url = $picture_url;

        return $this;
    }

    public function getLastDataUpdateAt(): ?\DateTimeImmutable
    {
        return $this->last_data_update_at;
    }

    public function setLastDataUpdateAt(?\DateTimeImmutable $last_data_update_at): self
    {
        $this->last_data_update_at = $last_data_update_at;

        return $this;
    }

    public function getLastPictureUpdateAt(): ?\DateTimeImmutable
    {
        return $this->last_picture_update_at;
    }

    public function setLastPictureUpdateAt(?\DateTimeImmutable $last_picture_update_at): self
    {
        $this->last_picture_update_at = $last_picture_update_at;

        return $this;
    }

    public function getPhotoAuthor(): ?string
    {
        return $this->photo_author;
    }

    public function setPhotoAuthor(?string $photo_author): self
    {
        $this->photo_author = $photo_author;

        return $this;
    }

    public function getPhotoLink(): ?string
    {
        return $this->photo_link;
    }

    public function setPhotoLink(?string $photo_link): self
    {
        $this->photo_link = $photo_link;

        return $this;
    }

    public function updateFromVRSData($vrsData)
    {
        $this->setCountry($vrsData['Country']);
        $this->setManufacturer($vrsData['Manufacturer']);
        $this->setModel($vrsData['Model']);
        $this->setModelIcao($vrsData['ModelIcao']);
        $this->setOperator($vrsData['Operator']);
        $this->setOperatorIcao($vrsData['OperatorIcao']);
        $this->setRegistration($vrsData['Registration']);
        $this->setSerial($vrsData['Serial']);
        $this->setYearBuild($vrsData['YearBuilt']);
        $this->setLastDataUpdateAt(new \DateTimeImmutable());
    }

    public function updatePhotoFromPlaneSpotters()
    {
        if ($this->getLastPictureUpdateAt() && $this->getLastPictureUpdateAt()->diff(new \DateTimeImmutable())->days < 1) {
            return false;
        }
        $url = 'https://api.planespotters.net/pub/photos/hex/' . $this->getIcao();
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_USERAGENT, 'IntelHub');
        $output = curl_exec($ch);
        curl_close($ch);
        $data = json_decode($output, true);
        if (count($data['photos']) > 0) {
            $this->setPictureUrl($data['photos'][0]['thumbnail_large']['src']);
            $this->setPhotoAuthor($data['photos'][0]['photographer']);
            $this->setPhotoLink($data['photos'][0]['link']);
            $this->setLastPictureUpdateAt(new \DateTimeImmutable());
            return true;
        }
        return false;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Form/AircraftType.php
<?php

namespace App\Form;

use App\Entity\Aircraft;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AircraftType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('icao')
            ->add('is_military')
            ->add('registration')
            ->add('country')
            ->add('manufacturer')
            ->add('model')
            ->add('model_icao')
            ->add('operator')
            ->add('operator_icao')
            ->add('serial')
            ->add('year_build');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Aircraft::class,
        ]);
    }
}

src/Controller/AircraftController.php
<?php

namespace App\Controller;

use App\Entity\Aircraft;
use App\Form\AircraftType;
use App\libs\VRSData;
use App\Repository\AircraftPositionRepository;
use App\Repository\AircraftRepository;
use Pagerfanta\Doctrine\ORM\QueryAdapter;
use Pagerfanta\Pagerfanta;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/aircraft')]
class AircraftController extends AbstractController
{
    #[Route('/', name: 'app_aircraft_index', methods: ['GET'])]
    public function index(AircraftRepository $aircraftRepository, Request $request): Response
    {
        $queryBuilder = $aircraftRepository->createQueryBuilder('a');
        $query = $request->get('q');
        if ($query) {
            $queryBuilder
                ->andWhere('a.registration LIKE :query')
                ->orWhere('a.icao LIKE :query')
                ->setParameter('query', '%' . strtoupper($query) . '%');
        }
        $adapter = new QueryAdapter($queryBuilder);
        $pagerFanta = Pagerfanta::createForCurrentPageWithMaxPerPage($adapter, $request->get('page', 1), 20);

        return $this->render('aircraft/index.html.twig', [
            'aircrafts' => $pagerFanta,
            'query' => $query,
        ]);
    }

    #[Route('/{icao}', name: 'app_aircraft_show', methods: ['GET'])]
    public function show(Aircraft $aircraft, AircraftRepository $aircraftRepository, AircraftPositionRepository $aircraftPositionRepository): Response
    {
        if ($aircraft->updatePhotoFromPlaneSpotters()) {
            $aircraftRepository->save($aircraft, true);
        }
        $lastAircraftPosition = $aircraftPositionRepository->getLastPosition($aircraft->getIcao());
        $isLiveTracking = $lastAircraftPosition && $lastAircraftPosition->getPositionAt() > new \DateTimeImmutable('-5 minutes');
        //seconds since last seen
        $secondsSinceLastSeen = $lastAircraftPosition ? time() - $lastAircraftPosition->getPositionAt()->getTimestamp() : 0;
        $lastSeenString = $secondsSinceLastSeen <= 90 ? "$secondsSinceLastSeen seconds ago" : ($secondsSinceLastSeen / 60) . ' minutes ago';
        return $this->render('aircraft/show.html.twig', [
            'aircraft' => $aircraft,
            'lastAircraftPosition' => $lastAircraftPosition,
            'isLiveTracking' => $isLiveTracking,
            'lastSeen' => $lastSeenString,
        ]);
    }

    #[Route('/{icao}/edit', name: 'app_aircraft_edit', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_ADMIN')]
    public function edit(Request $request, Aircraft $aircraft, AircraftRepository $aircraftRepository): Response
    {
        $form = $this->createForm(AircraftType::class, $aircraft);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $aircraftRepository->save($aircraft, true);

            return $this->redirectToRoute('app_aircraft_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('aircraft/edit.html.twig', [
            'aircraft' => $aircraft,
            'form' => $form,
        ]);
    }

    #[Route('/{icao}', name: 'app_aircraft_delete', methods: ['POST'])]
    #[IsGranted('ROLE_ADMIN')]
    public function delete(Request $request, Aircraft $aircraft, AircraftRepository $aircraftRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $aircraft->getId(), $request->request->get('_token'))) {
            $aircraftRepository->remove($aircraft, true);
        }

        return $this->redirectToRoute('app_aircraft_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/{icao}/data-update', name: 'app_aircraft_update_details', methods: ['GET'])]
    #[IsGranted('ROLE_ADMIN')]
    public function dataUpdate(Request $request, Aircraft $aircraft, AircraftRepository $aircraftRepository): Response
    {
        $vrsData = new VRSData();
        $data = $vrsData->getAircraftData([$aircraft->getIcao()]);
        $vrsDataResult = VRSData::findAircraft($data, $aircraft->getIcao());
        if (!empty($vrsDataResult)) {
            $aircraft->updateFromVRSData($vrsDataResult);
            $aircraftRepository->save($aircraft, true);
            $this->addFlash('success', 'Aircraft data updated');
        } else {
            $this->addFlash('warning', 'Aircraft data not found');
        }
        return $this->redirectToRoute('app_aircraft_show', ['icao' => $aircraft->getIcao()], Response::HTTP_SEE_OTHER);
    }
}

templates/aircraft/_delete_form.html.twig
<form method="post"
      action="{{ path('app_aircraft_delete', {'icao': aircraft.icao}) }}"
      onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ aircraft.id) }}">
    <button class="btn">Delete</button>
</form>

templates/aircraft/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Aircraft{% endblock %}

{% block body %}
    <h1>Edit Aircraft</h1>

    {{ include('aircraft/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_aircraft_index') }}">back to list</a>

    {{ include('aircraft/_delete_form.html.twig') }}
{% endblock %}

templates/aircraft/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Aircraft index{% endblock %}

{% block body %}
    <h2 class="intro-y text-lg font-medium mt-10">
        Aircrafts </h2>
    <div class="intro-y col-span-12 flex flex-wrap sm:flex-nowrap items-center mt-2">
        <div class="w-full sm:w-auto mt-3 sm:mt-0 sm:ml-auto md:ml-0">
            <div class="w-56 relative text-slate-500">
                <form action="{{ path('app_aircraft_index') }}"
                      method="get">
                    <input type="text"
                           name="q"
                           class="form-control w-56 box pr-10"
                           placeholder="Search ICAO/Registration"
                           value="{{ query }}">
                </form>
                <i class="w-4 h-4 absolute my-auto inset-y-0 mr-3 right-0"
                   data-lucide="search"></i>
            </div>
        </div>
    </div>
    <div class="intro-y col-span-12 overflow-auto lg:overflow-visible">
        <table class="table table-report -mt-2">
            <thead>
            <tr>
                <th class="whitespace-nowrap">PIC</th>
                <th class="text-center whitespace-nowrap">ICAO</th>
                <th class="text-center whitespace-nowrap">REG</th>
                <th class="text-center whitespace-nowrap">MODEL</th>
                <th class="text-center whitespace-nowrap">TYPE</th>
                <th class="text-center whitespace-nowrap">COUNTRY</th>
                <th class="text-center whitespace-nowrap">ACTIONS</th>
            </tr>
            </thead>
            <tbody>
            {% for aircraft in aircrafts %}
                <tr class="intro-x">
                    <td class="w-40">
                        <div class="flex">
                            <div class="w-10 h-10 image-fit zoom-in">
                                {% if aircraft.pictureUrl %}

                                    <img alt="Aircraft picture"
                                         class="tooltip rounded-full"
                                         src="{{ aircraft.pictureUrl }}"
                                         title="Aircraft picture">
                                {% else %}
                                    <img alt="Aircraft picture"
                                         class="tooltip rounded-full"
                                         src="https://via.placeholder.com/150"
                                         title="Aircraft picture">
                                {% endif %}
                            </div>
                        </div>
                    </td>
                    <td>
                        <a href=""
                           class="font-medium whitespace-nowrap">{{ aircraft.icao }}</a>
                        {#                        <div class="text-slate-500 text-xs whitespace-nowrap mt-0.5">Electronic</div> #}
                    </td>
                    <td class="text-center">{{ aircraft.registration }}</td>
                    <td class="text-center">{{ aircraft.model }}</td>
                    <td class="text-center">{{ aircraft.isMilitary ? 'Military': 'Civilian' }}</td>
                    <td class="text-center">{{ aircraft.country }}</td>
                    <td class="table-report__action w-56">
                        <div class="flex justify-center items-center">
                            <a class="flex items-center mr-3"
                               href="{{ path('app_aircraft_show', {'icao': aircraft.icao}) }}">
                                <i data-lucide="eye"
                                   class="w-4 h-4 mr-1"></i> View
                            </a>
                        </div>
                    </td>
                </tr>
                {#                <tr class="text-center"> #}
                {#                    <td class="border px-4 py-2 w-1/4">{{ aircraft.icao }}</td> #}
                {#                    <td class="border px-4 py-2 w-1/4">{{ aircraft.registration }}</td> #}
                {#                    <td class="border px-4 py-2 w-1/4">{{ aircraft.model }}</td> #}
                {#                    <td class="border px-4 py-2 w-1/4">{{ aircraft.country }}</td> #}
                {#                    <td class="border px-4 py-2 w-1/4"> #}
                {#                        {% if aircraft.isIsMilitary == 1 %} #}
                {#                            <span class="rounded-full p-2 bg-green-500 text-white">Yes</span> #}
                {#                        {% else %} #}
                {#                            <span class="rounded-full p-2 bg-red-500 text-white">No</span> #}
                {#                        {% endif %} #}
                {#                    </td> #}

                {#                    <td class="border px-4 py-2 w-1/4"> #}
                {#                        <a href="{{ path('app_aircraft_show', {'icao': aircraft.icao}) }}" #}
                {#                           class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded"> #}
                {#                            View #}
                {#                        </a> #}
                {#                        {% if is_granted('ROLE_ADMIN', app.user) %} #}
                {#                            <br> #}
                {#                            <a href="{{ path('app_aircraft_edit', {'icao': aircraft.icao}) }}" #}
                {#                               class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"> #}
                {#                                Edit #}
                {#                            </a> #}
                {#                        {% endif %} #}
                {#                    </td> #}

                {#                </tr> #}
            {% endfor %}
            </tbody>
        </table>
    </div>

    {{ pagerfanta(aircrafts) }}
{% endblock %}